namespace DbTracer.MsSql
{
    public enum ScripActionType
    {
        None = 0,
        UseDatabase = 1,
        AddFileGroup = 2,
        AddFile = 3,
        AlterFile = 4,
        AlterFileGroup = 5,
        UnbindRuleColumn = 6,
        UnbindRuleType = 7,
        DropRule = 8,
        AddRule = 9,

        DropFullTextIndex = 10,
        DropConstraintFk = 11,
        DropConstraint = 12,
        DropConstraintPk = 13,
        DropSynonyms = 14,
        DropStoreProcedure = 15,
        DropTrigger = 16,
        DropView = 17,
        DropFunction = 17,
        DropIndex = 18,
        DropTable = 20,
        AlterColumnFormula = 21,
        AlterColumn = 22,
        AddRole = 23,
        AddUser = 24,
        AddSchema = 25,
        AddDefault = 26,
        AddAssembly = 27,
        AddAssemblyFile = 28,
        AddUserDataType = 29,
        AddTableType = 30,
        AlterPartitionFunction = 31,
        AddPartitionFunction = 32,
        AddPartitionScheme = 33,
        AddFullText = 34,
        AddXmlSchema = 35,
        AlterAssembly = 36,
        UpdateTable = 37,
        AlterTable = 38,
        AlterIndex = 39,
        AlterFullTextIndex = 40,
        AddTable = 41,
        RebuildTable = 42,
        AlterColumnRestore = 43,
        AlterColumnFormulaRestore = 44,
        AlterFunction = 45,
        AlterView = 46,
        AlterProcedure = 47,
        AddIndex = 48,
        AddFunction = 49,
        AddView = 49, /*AddFunction and AddView must have the same number!!!*/
        AddTrigger = 50,
        AddConstraint = 51,
        AddConstraintPk = 52,
        AddConstraintFK = 53,
        AlterConstraint = 54,
        AddFullTextIndex = 55,
        EnabledTrigger = 56,
        AddSynonyms = 57,
        AddStoreProcedure = 58,
        DropOptions = 59,
        AddOptions = 60,

        AlterTableChangeTracking = 61,

        DropFullText = 62,
        DropTableType = 63,
        DropUserDataType = 64,
        DropXmlSchema = 65,
        DropAssemblyUserDataType = 66,
        DropAssemblyFile = 67,
        DropAssembly = 68,
        DropDefault = 69,

        DropPartitionScheme = 70,
        DropPartitionFunction = 71,

        DropSchema = 72,
        DropUser = 73,
        DropRole = 74,
        DropFile = 75,
        DropFileGroup = 76,
        AddExtendedProperty = 77,
        DropExtendedProperty = 78
    }
}